### ISSUE TITLE
Issue with the TXT files

### ISSUE THREAD

**Issue by ZlataKikteva** [juliandehne/delab#19]
The txt file of the full conversation (1442610555311722509_conversation_full.txt) from the first twitter zip-file is missing some tweets which are included in the excel file (1442610555311722509_conversation_full.xlsx). E.g. tweets with IDs 1073, 1075 and some others. I don't know if there is the same issue for other txt files.

**Comment by juliandehne** [comment]
The problem lies in the way the conversation tree is constructed in Twitter. Responses are defined as "reply to author x". However, if someone posts more then one post, the correct interpretation might be "reply to last post by author x". But that is just an assumption. The twitter api is not clear on that. Basically, there are multiple ways of reconstructing the tree. Currently, I have no solution.
